pub const VesaBlock = packed struct {
    modeAttributes: u16,
    winAAttributes: u8,
    winBAttributes: u8,
    winGranularity: u16,
    winSize: u16,
    winASegment: u16,
    winBSegment: u16,
    winFuncPtr: u32,
    bytesPerScanLine: u16,
    xResolution: u16,
    yResolution: u16,
    xCharSize: u8,
    yCharSize: u8,
    numberOfPlanes: u8,
    bitsPerPixel: u8,
    numberOfBanks: u8,
    memoryModel: u8,
    bankSize: u8,
    numberOfImagePages: u8,
    reserved1: u8,

    redMaskSize: u8,
    redFieldPosition: u8,
    greenMaskSize: u8,
    greenFieldPosition: u8,
    blueMaskSize: u8,
    blueFieldPosition: u8,
    rsvdMaskSize: u8,
    rsvdFieldPosition: u8,
    directColorModeInfo: u8,

    physicalBasePtr: u32,
    offScreenMemOffset: u32,
    offScreenMemSize: u16,
    reserved: [206]u8,
};

pub const VBE_ADDRESS: u32 = 0x1000;
